### ISSUE TITLE
Cannot generate recommendation from a collection

### ISSUE THREAD

**Issue by Bunoute** [impresso/impresso-frontend#1016]
error message: { "route": [ "articles-recommendations", "create" ], "message": "server error", "code": 500, "name": "GeneralError" } paths.articles-recommendations.create
URL:
https://dev.impresso-project.ch/app/collections/local-eb-rl98Hh4W?tab=recommendations

**Comment by Bunoute** [comment]
same for this one: https://dev.impresso-project.ch/app/collections/local-eb-WkV_7tIp?tab=recommendations
(could it be that the collection is too big? It worked for this one: https://dev.impresso-project.ch/app/collections/local-eb-dbs6v567?tab=recommendations )

**Comment by theorm** [comment]
@Bunoute would you be able to paste here links _and_ parameters of the filters you used in the recommendation tab? We do not have deep linking for recommendations page which means there are no filter parameters in the URL.

**Comment by theorm** [comment]
Meanwhile I had a look in the logs of the middle layer and I see messages like this:

```
ERROR invalid-json FetchError at articles-recommendations:create:  FetchError: invalid json response body at https://dev.impresso-project.ch/recsys/recommend/ reason: Unexpected token < in JSON at position 0
    at /impresso-middle-layer/node_modules/node-fetch/lib/index.js:272:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

It hints that there is a certain recommender filter combination that makes the recommender crash. @danieleguido it might be worth picking a recommender request that consistently crashes the recommender and debug the recommender directly, possibly running locally.

**Comment by Bunoute** [comment]
test results:

for Paris-Roubaix with TMs mixed sports
saved in Paris-Roubaix w. WE; with topic monde · concours · record · sport · suisse or match · équipe · ligue · club · saison or bat · finale · tour · tournoi · match or match · jeu · but · équipe · minute
https://dev.impresso-project.ch/app/collections/local-eb-ssQqIDP8?tab=recommendations 
no articles found


for the collection Paris-Roubaix-simple
containing paris roubaix, for which it did not work previously: very nice results!

and same for the collection initially mentioned here

**Comment by Bunoute** [comment]
<img width="1237" alt="Screenshot 2020-09-24 at 17 34 01" src="https://user-images.githubusercontent.com/32094266/94166951-3cf83f00-fe8c-11ea-852e-69b75a68f139.png">
<img width="1237" alt="Screenshot 2020-09-24 at 17 33 55" src="https://user-images.githubusercontent.com/32094266/94166958-3d90d580-fe8c-11ea-9588-b9234e34a9bf.png">
<img width="1237" alt="Screenshot 2020-09-24 at 17 33 50" src="https://user-images.githubusercontent.com/32094266/94166960-3e296c00-fe8c-11ea-86a9-97b2e51db92c.png">
<img width="1237" alt="Screenshot 2020-09-24 at 17 33 44" src="https://user-images.githubusercontent.com/32094266/94166961-3e296c00-fe8c-11ea-9e22-07898890b6b3.png">
<img width="1237" alt="Screenshot 2020-09-24 at 17 33 32" src="https://user-images.githubusercontent.com/32094266/94166965-3ec20280-fe8c-11ea-8382-00f4bffcbcc3.png">

**Comment by Bunoute** [comment]
eb-LedVgPg5

eb-edseIRGr

eb-rl98Hh4W

eb-WkV_7tIp

eb-ssQqIDP8

**Comment by mduering** [comment]
Recommendations tab is gone
