### ISSUE TITLE
Error: errors.BadGateway.SequelizeDatabaseError

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#1286]
https://dev.impresso-project.ch/app/search?sq=CgIYAgoZEAIYEyoTbG9jYWwtZHVtYS1TRV9KNUcwZQoeCAEQAhgSKhZ0bS1mci1hbGwtdjIuMF90cDE3X2ZyCggQAhgWKgJDSAoIEAIYDSoCYWQKMhACGAoqLDE5NzktMDEtMDFUMDA6MDA6MDBaIFRPIDE5NzktMTItMzFUMjM6NTk6NTla

disappeared upon refresh

**Comment by theorm** [comment]
A bit more context from the server logs:

```
  original: Error: Error writing file '/tmp/MYfd=146' (OS errno 28 - No space left on device)
      at Packet.asError (/impresso-middle-layer/node_modules/mysql2/lib/packets/packet.js:728:17)
      at Query.execute (/impresso-middle-layer/node_modules/mysql2/lib/commands/command.js:29:26)
      at Connection.handlePacket (/impresso-middle-layer/node_modules/mysql2/lib/connection.js:456:32)
      at PacketParser.onPacket (/impresso-middle-layer/node_modules/mysql2/lib/connection.js:85:12)
      at PacketParser.executeStart (/impresso-middle-layer/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/impresso-middle-layer/node_modules/mysql2/lib/connection.js:92:25)
      at Socket.emit (node:events:519:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Readable.push (node:internal/streams/readable:390:5)
      at TCP.onStreamRead (node:internal/stream_base_commons:191:23) {
    code: 'EE_WRITE',
    errno: 3,
    sqlState: 'HY000',
    sqlMessage: "Error writing file '/tmp/MYfd=146' (OS errno 28 - No space left on device)",
```

**Comment by theorm** [comment]
Looks like there is enough space at the moment. I did prune the unused docker object though and reclaimed some extra space:

```
docker system prune

Total reclaimed space: 9.657GB
```
