### ISSUE TITLE
socket-io: max call stack exceeded

### ISSUE THREAD

**Issue by theorm** [impresso/impresso-frontend#1343]
Likely an object with circular references is sent down a socket-io connection to the server

```
[impresso.middle-layer] [WebApp Error] {"id":"4d86b44c-80e5-4125-b12b-8849b7cb90bd","url":"https://dev.impresso-project.ch/app/collections/local-t9FZDTQi-E0JEiUyD","errorMessage":"Maximum call stack size exceeded","stackTrace":"RangeError: Maximum call stack size exceeded\n    at hasBinary (/impresso-middle-layer/node_modules/socket.io-parser/build/cjs/is-binary.js:28:19)\n    at hasBinary (/impresso-middle-layer/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)\n    at hasBinary (/impresso-middle-layer/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)\n    at hasBinary (/impresso-middle-layer/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)\n    at hasBinary (/impresso-middle-layer/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)\n    at hasBinary (/impresso-middle-layer/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)\n    at hasBinary (/impresso-middle-layer/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)\n    at hasBinary (/impresso-middle-layer/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)\n    at hasBinary (/impresso-middle-layer/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)\n    at hasBinary (/impresso-middle-layer/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)\n    at hasBinary (/impresso-middle-layer/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)\n    at hasBinary (/impresso-middle-layer/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)\n    at hasBinary (/impresso-middle-layer/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)\n    at hasBinary (/impresso-middle-layer/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)\n    at hasBinary (/impresso-middle-layer/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)\n    at hasBinary (/impresso-middle-layer/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)","origin":"unhandledrejection","userId":"local-xxx","timestamp":"2024-10-16T09:16:14.754Z"}
```

**Comment by danieleguido** [comment]
it's the good old celery in IML
